#!/usr/bin/env python
# File Name: 16-7ser.py

from time import ctime
from socket import *

HOST = ''
PORT = 21456
BUFSIZ = 1024
ADDR = (HOST, PORT)

udpSerSock = socket(AF_INET, SOCK_DGRAM)
udpSerSock.bind(ADDR)
ans = getservbyname('datatime','udp')
print ans
while True:
    print 'waiting'
    data, addr = udpSerSock.recvfrom(BUFSIZ)
    udpSerSock.sendto('[%s] %s'%(ctime(), data), addr)

udpSerSock.close
